ALLOWED_TOPICS = [
    "edify",
    "company",
    "location",
    "contact",
    "services",
    "data science",
    "machine learning",
    "clinical research",
    "cdisc",
    "team",
    "projects",
    "software development",
    "technologies",
    "testimonials",
    "experience",
    "news",
]
